;Registros del PIC
EOI EQU 20H
IMR EQU 21H
IRR EQU 22H
ISR EQU 23H
INT0 EQU 24H
INT1 EQU 25H
INT2 EQU 26H
INT3 EQU 27H

;Valores especiales
MASCARA_F10 EQU 11111110B ; En hexadecimal 0FEH
VALOR_FIN_INTERRUPCION EQU 20H
LETRA_A EQU 41H
LETRA_Z EQU 5AH
SALTO_DE_LINEA EQU 0AH

;Vector de Interrupciones
ID_F10 EQU 10 ; Elegido  de forma arbitraria

ORG 40; El valor de ID_F10  multiplicado por 4
DW RUTINA_INTERRUPCION_F10; No es necesario ponerle una etiqueta

ORG 1000H
CAR_SELECCIONADO DB ?, SALTO_DE_LINEA

ORG 3000H
RUTINA_INTERRUPCION_F10: PUSH AX
PUSH BX
MOV BX, OFFSET CAR_SELECCIONADO
MOV BYTE PTR [BX], DL
MOV AL, 2
INT 7; Imprime la letra seleccionada por tecla F_10 + Salto de linea
MOV AL, VALOR_FIN_INTERRUPCION
OUT EOI, AL
POP AX
POP BX
IRET

ORG 2000H
CLI
MOV AL, MASCARA_F10
OUT IMR, AL
MOV AL, ID_F10
OUT INT0, AL
STI
REINICIAR_SECUENCIA: MOV DL, LETRA_A
LOOP_INFINITO: CMP DL, LETRA_Z
JZ REINICIAR_SECUENCIA
INC DL
JMP LOOP_INFINITO
INT 0 ; Codigo inalcanzable ajjajajajajjajajajajaja
END

