;Registros del TIMER
CONT EQU 10H
COMP EQU 11H

;Registros del PIC
;Registros del PIC
EOI EQU 20H
IMR EQU 21H
IRR EQU 22H
ISR EQU 23H
INT0 EQU 24H
INT1 EQU 25H
INT2 EQU 26H
INT3 EQU 27H

;Valores especiales
MASCARA_TIMER EQU 11111101B; En hexadecimal 0FDH
VALOR_FIN_INTERRUPCION EQU 20H
CERO EQU 30H; Digito '0'
SEIS EQU 36H; Digito '6'
DOS_PUNTOS EQU 3AH; Simbolo ':'

N_CLK EQU 10
ORG 40
DW RUTINA_CLK

ORG 1000H
SEG1 DB CERO
SEG2 DB CERO
FIN DB ?

ORG 3000H
RUTINA_CLK: PUSH AX
INC SEG2
CMP SEG2, DOS_PUNTOS
JNZ RESET
MOV SEG2, CERO
INC SEG1
CMP SEG1, SEIS
JNZ RESET
MOV SEG1, CERO
RESET: INT 7
MOV AL, 0
OUT CONT, AL
MOV AL, VALOR_FIN_INTERRUPCION
OUT EOI, AL
POP AX
IRET

ORG 2000H
CLI
MOV AL, MASCARA_TIMER
OUT IMR, AL ; PIC: registro IMR
MOV AL, N_CLK
OUT INT1, AL ; PIC: registro INT1
MOV AL, 1
OUT COMP, AL ; TIMER: registro COMP
MOV AL, 0
OUT CONT, AL ; TIMER: registro CONT
MOV BX, OFFSET SEG1
MOV AL, OFFSET FIN-OFFSET SEG1
STI
LAZO: JMP LAZO
END

