ORG 1000H
MSJ1 DB "INGRESE UN NUMERO: "
FIN1 DB ?
MSJ2 DB "CARACTER NO VALIDO"
FIN2 DB ?
MSJ3 DB "CARACTER VALIDO"
FIN3 DB ?
SALTO_DE_LINEA DB 0AH
NUM DB ?


ORG 3000H
ES_NUM: CMP BYTE PTR [BX], 30H
JS NO_ES_NUMERO ; COMO DECIR SI EL CARACTER ES MENOR AL CARACTER '0'
MOV DL, 39H
CMP DL, [BX] ; COMO DECIR SI EL CARACTER ES MAYOR AL CARACTER '9'
JS NO_ES_NUMERO
MOV DL, 0FFH
JMP FIN_SUBRUTINA
NO_ES_NUMERO: MOV DL, 00H
FIN_SUBRUTINA: RET 

ORG 2000H
MOV BX, OFFSET MSJ1
MOV AL, OFFSET FIN1-OFFSET MSJ1
INT 7

MOV BX, OFFSET NUM
INT 6

MOV BX, OFFSET NUM
MOV AL, 1
INT 7

CALL ES_NUM

MOV BX, OFFSET SALTO_DE_LINEA
MOV AL, 1
INT 7

CMP DL, 0FFH
JZ IMPRIME_MENSAJE3
MOV BX, OFFSET MSJ2
MOV AL, OFFSET FIN2-OFFSET MSJ2
JMP FIN
IMPRIME_MENSAJE3: MOV BX, OFFSET MSJ3
MOV AL, OFFSET FIN3-OFFSET MSJ3
FIN: INT 7

INT 0
END

