ORG 1000H
CLAVE DB "av84"
FIN_CLAVE DB ?

MSJ1 DB "Ingrese la clave(4 caracteres): "
     DB 0AH ; SALTO DE LINEA
FIN_MSJ1 DB ?

MSJ2 DB "Acceso permitido"
FIN_MSJ2 DB ?

MSJ3 DB "Acceso denegado"
FIN_MSJ3 DB ?

CLAVE_LEIDA DB ?,?,?, ?
FIN_CLAVE_LEIDA DB ?

ORG 2000H
MOV BX, OFFSET MSJ1
MOV AL, OFFSET FIN_MSJ1 - OFFSET MSJ1
INT 7

MOV BX, OFFSET CLAVE_LEIDA
MOV AL, OFFSET FIN_CLAVE_LEIDA - OFFSET CLAVE_LEIDA
LEER_CARACTER: CMP AL, 0
JZ SIGO
INT 6
INC BX
DEC AL
JMP LEER_CARACTER

SIGO: MOV CX, OFFSET CLAVE
MOV DX, OFFSET CLAVE_LEIDA
LOOP_COMPARAR: MOV BX, CX
CMP BX, OFFSET FIN_CLAVE
JZ SON_IGUALES
MOV AL, [BX]
MOV BX, DX
MOV AH, [BX]
CMP AL, AH
JNZ NO_SON_IGUALES
INC CX
INC DX
JMP LOOP_COMPARAR

NO_SON_IGUALES: MOV BX, OFFSET MSJ3
MOV AL, OFFSET FIN_MSJ3 - OFFSET MSJ3
JMP MOSTRAR_MENSAJE
SON_IGUALES: MOV BX, OFFSET MSJ2
MOV AL, OFFSET FIN_MSJ2 - OFFSET MSJ2
MOSTRAR_MENSAJE: INT 7
FIN: INT 0
END

