ORG 1000H
NUM1 DW 1234H
	    2345H
NUM2 DW 6789H
        8923H
RES DW ?
	   ?
	   
ORG 3000H
SUM32: PUSH BX; Salva Viejo BX(PARA QUE CORNOS HACEN ESTO??? BUENO LO DEJO COMO ESTA EN LA PRACTICA AJJAJAJAJAJJA )
MOV BX, SP; Salva registro SP(STACK POINTER)

ADD BX, 14
MOV CX, [BX]; OBTENER PARTE BAJA DE NUM1

SUB BX, 2
MOV DX, [BX]; OBTENER PARTE ALTA DE NUM1

SUB BX, 2
MOV AX, [BX]; OBTENER PARTE BAJA DE NUM2

SUB BX, 2; APUNTAR BX A LA PARTE ALTA DE NUM2

ADD CX, AX; SUMAR PARTES BAJAS DE NUM1 Y NUM2
ADC DX, [BX]; SUMAR PARTES ALTAS DE NUM1 Y NUM;

SUB BX, 2;
MOV BX, [BX] ; OBTENER DIRECCION DE VARIABLE RES

MOV [BX], CX ; GUARDAR RESULTADO PARTE BAJA
ADD BX, 2
MOV [BX], DX; GUARDAR RESULTADO PARTE ALTA

POP BX
RET
	 
ORG 2000H
MOV AX, NUM1
PUSH AX
MOV AX, NUM1+2
PUSH AX
MOV AX, NUM2
PUSH AX
MOV AX, NUM2+2
PUSH AX
MOV AX, OFFSET RES
PUSH AX
CALL SUM32
POP AX
POP AX
POP AX 
POP AX 
POP AX 
HLT
END